version: '3'

services:
  template:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - "./configs:/app/configs"
    ports:
      - '8080:8080'
    depends_on:
      db:
        condition: service_healthy
    networks:
      - auth2db

  db:
    image: postgres:15.1
    hostname: db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: auth
      PGDATA: "/var/lib/postgresql/data/pgdata"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 128M
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d auth" ]
      interval: 5s
      timeout: 5s
      retries: 100
      start_period: 10s
    networks:
      - auth2db

networks:
  auth2db:
    driver: bridge
