port: 8081

db:
  schema: "postgres"
  user: "user"
  password: "password"
  ip: "db"
  port: 5432
  database: "auth"
  ssl: "disable"
  migrations_path: file://migrations

clients:
  example:
    url: http://localhost:8081

logger:
  mode: debug
