name: Publish

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  auth:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out
        uses: actions/checkout@v4

      - name: Log in Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Set up Docker BuildX
        uses: docker/setup-buildx-action@v3
      
      - name: Extract GateWay Metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKER_USERNAME }}/auth

      - name: Build and Push Auth
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/auth:${{ github.sha }}
          labels: ${{ steps.meta.outputs.labels }}

  operations:
    runs-on: ubuntu-latest
    needs:
      - auth
    steps:
      - name: Check Out
        uses: actions/checkout@v4
        with:
          repository: hse-telescope/operations
          ref: master
          token: ${{ secrets.OPERATIONS_REPO_UPDATE }}

      - name: Setup Git Config
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Update Staging Tag
        if: ${{ github.ref != 'refs/heads/master' }}
        run: |
          sed -i 's/AUTH_TAG=.*/AUTH_TAG=${{ github.sha }}/g' ./compose/staging/.env
          sed -i 's/  migrations_path:.*/  migrations_path: github://hse-telescope/auth/migrations#${{ github.sha }}/g' ./compose/staging/configs/auth.yaml

          git add ./compose/staging/.env
          git add ./compose/staging/configs/auth.yaml

          # If script has been run twice on the same commit
          git commit --allow-empty -m "Tag update: ${{ github.sha }}"
          git push

      - name: Update Production Tag
        if: ${{ github.ref == 'refs/heads/master' }}
        run: |
          sed -i 's/AUTH_TAG=.*/AUTH_TAG=${{ github.sha }}/g' ./compose/production/.env

          git add ./compose/production/.env

          # If script has been run twice on the same commit
          git commit --allow-empty -m "Tag update: ${{ github.sha }}"
          git push
